Fix issues with nl_inside_empty_func
uncrustify/uncrustify pull request #3006
Opened 2020-12-09 07:11 UTC by parkerjs

This commit addresses issues that arise when 'nl_inside_empty_func'
is used in conjunction with 'eat_blanks_before_close_brace' or
'eat_blanks_after_open_brace'. The problem occurs when a line is
split according to code width constraints imposed by the
'code_width' option. It turns out that the 'nl_max_blank_in_func'
was also ignored for similar reasons, and as such an additional
call to newlines_functions_remove_extra_blank_lines() is made
after a call to do_code_width() *if* a change results from
imposing line width constraints.

2020-12-09 16:15 UTC, guy-maurel commented on src/newlines.cpp
> +         if (  options::nl_inside_empty_func()
Please change to:
if (  options::nl_inside_empty_func() > 0

2020-12-09 16:16 UTC, guy-maurel commented on src/newlines.cpp
> +         else if (  options::nl_inside_namespace()
and here to:
else if (  options::nl_inside_namespace() > 0

2020-12-09 16:17 UTC, guy-maurel commented on src/newlines.cpp
> +               if (  options::nl_inside_empty_func()
also here

2020-12-09 16:17 UTC, guy-maurel commented on src/newlines.cpp
> +               else if (  options::nl_inside_namespace()
and here

2020-12-09 16:19 UTC, guy-maurel requested changes
have a look to my comments

2020-12-10 16:41 UTC, gmaurel approved these changes

2020-12-10 16:41 UTC, merged