Fix for issue 3061
uncrustify/uncrustify pull request #3095
Opened 2021-02-10 12:05 UTC by micheleCTDE

This issue was introduced by commit 313f6eb7 (PR #3014).

'void newlines_remove_disallowed()' should not eat new line characters
in the following cases:
1. we are at the end of the file
2. there are consecutive new line characters
because that is already dealt with in a different part of the code.

Tests with different combinations of existing and required numbers of nl are included. 4 sets, each set requiring a different number of nl on 3 different files with different original numbers of nl. This tests adding nl, removing nl, leaving nl unchanged at the end of the file.

2021-02-12 16:58 UTC, gmaurel requested changes

2021-02-12 16:58 UTC, gmaurel commented on src/newlines.cpp
> +      if (  next
Please use:
if ( next != nullptr
...

2021-02-13 02:09 UTC, micheleCTDE commented on src/newlines.cpp
> +      if (  next
updated as required

2021-02-13 16:40 UTC, gmaurel approved these changes
Thanks

2021-02-13 16:40 UTC, merged