add nl_before_struct option
uncrustify/uncrustify pull request #3193
Opened 2021-05-28 06:15 UTC by gg-yb

This works similar to nl_before_class, but the option to modify newlines
before structs is somehow missing, as far as I can see.

Currently, we can do the following:

```cpp
int foo = 1;
class Bar {};
int baz = 2;
```

and

```
nl_before_class = 2
```

and we obtain

```cpp
int foo = 1;

class Bar {};
int baz = 2;
```

Alas, when we have

```cpp
int foo = 1;
struct Bar {};
int baz = 2;
```

this is currently not possible.

2021-05-28 09:29 UTC, gmaurel requested changes
Please go to:
  https://github.com/gg-yb/uncrustify/actions
and activate the workflow(s)

2021-05-28 10:42 UTC, gg-yb commented
Thanks for your feedback, I enabled the workflows.

2021-05-31 06:06 UTC, gg-yb commented
I have pushed a change, see the action here https://github.com/gg-yb/uncrustify/actions/runs/891858037

2021-05-31 15:04 UTC, gmaurel approved these changes

2021-05-31 15:04 UTC, merged