Refactor a few chunk tests and matching tools
uncrustify/uncrustify pull request #3207
Opened 2021-06-12 15:13 UTC by parkerjs

- Introduced more functions to standardize tests for chunk token types
  and strings

- Also moved some chunk sequence matching subroutines out of
  EnumStructUnionParser and into a new cpp file so that these
  subroutines may be used by others

2021-06-14 12:36 UTC, gmaurel requested changes
Please complete the comment with your name.
It would be appropriate to write something such as:
...
extraxt from the file xyz.cpp or xyz.h
adapted by ...

Thanks

2021-06-14 13:10 UTC, mwoehlke-kitware requested changes
Whee...

TBH, I fail to see the value here, at least in its current state. Replacing `chunk_is_token` with dozens of individual functions for each token type is IMO definitely *not* an improvement; it adds a huge amount of code for (again, IMO) exactly zero benefit.

Ultimately, Guy is the maintainer, but my vote would be to ***at minimum*** get rid of all of those. Better would be to start with one function that is actually useful (combines several tests and is used in several places) and see how that goes over (right now there is just so much churn it's hard to separate what might be useful from the noise). Then repeat for what other such functions may exist.

At the very least, this is too big to be reasonably reviewed.

2021-06-14 13:26 UTC, parkerjs commented
> 
> 
> Whee...
> 
> TBH, I fail to see the value here, at least in its current state. Replacing `chunk_is_token` with dozens of individual functions for each token type is IMO definitely _not_ an improvement; it adds a huge amount of code for (again, IMO) exactly zero benefit.
> 
> At the very least, this is too big to be reasonably reviewed.

I was in the midst of refactoring the manner in which templates are interpreted, similar to the manner in which I created the EnumStructUnionParser class (which corrected quite a few erroneous chunk classifications). Uncrustify still misinterprets comparison angle brackets for templates and vice versa, and I had planned to break up all of my work into pieces to make it more manageable. But if that is your attitude, then I withdraw my commit entirely.

2021-06-14 13:27 UTC, closed without merging

2021-06-14 15:12 UTC, mwoehlke-kitware commented
Touchy, much?

There are certainly ways in which parsing could use improvement. However, it is unclear how `chunk_is_brace_open_token(pc)` is superior to `chunk_is_token(pc, CT_BRACE_OPEN)`. Maybe you could enlighten us?

There may be useful changes here, but it's hard to tell given the level of churn. Smaller pieces are better.

2021-06-14 15:17 UTC, mwoehlke-kitware commented
Short version: this is a very large change, and lacks adequate explanation as to its purpose. Therefore, please elucidate your objectives.

2021-06-14 15:34 UTC, parkerjs commented
Perhaps I am a bit touchy, but I don't react well to those who are extremely condescending. Please forget that I initiated this pull request, let's just drop it.

2021-06-14 18:45 UTC, mwoehlke-kitware commented
I apologize if you feel I am being condescending. That was not my intention, but please try to not take things so personally. It's not uncommon for software developers to not devote a lot of time to mincing words.

I don't want to discourage you from contributing, but please be considerate of those that might not know *why* you are are making a particular change (noting these details *in the commit log*, not just on GitHub, is strongly preferred), and also that very large PRs are difficult to review, particularly if a lot of "automated" changes are mixed in with more interesting changes.

That said... I'm sorry, but I *am* concerned with parts of this change. It adds a significant corpus of highly repetitive code, which is exactly *opposite* many refactorings, and, as I said originally, the justification for doing so is not apparent. I assume there must be *some* reason, since you obviously went to a non-trivial effort to *make* those changes, and I'd be very interested to know why.

2021-06-15 14:53 UTC, gmaurel commented
Thanks for your proposal! YES, thanks!
I think, "closing" is not the right way. You should re-open the PR.
"Re-open" makes some discuss possible.
@mwoehlke-kitware makes lot questions, you should try to answer, please.
A discuss is always the best manner to find the best solution (I have about 50 years experience),
even if it might be difficult to accept some opinion(s).