Fix comment for option nl_create_list_one_liner in default.cfg
uncrustify/uncrustify pull request #3221
Opened 2021-06-28 16:20 UTC by hghdev

The comment for option nl_create_list_one_liner refers to unbraced if statements. The name of the option and the given example refer to list definitions.

2021-06-30 14:56 UTC, gmaurel requested changes
you should make the proposed change **ONLY** in the file options.h
The new build will generate the new files as necessary.
Never change those files as here  _documentation/htdocs/default.cfg_

2021-06-30 15:17 UTC, mwoehlke-kitware commented
What Guy said. Also, after updating, run `make update-cli-options` / `ninja update-cli-options`, which will propagate the changes to all the generated files.

As is, the tests will fail and the next time someone regenerated the generated stuff, your change will be lost.

2021-07-02 13:54 UTC, mwoehlke-kitware commented
Hi, @hghdev! Can you please squash this into a single commit? Also, you need to run `cmake --build path/to/uncrustify/build --target update-cli-options` to update all the files that are generated from `options.h` and commit those changes also.

2021-07-02 15:55 UTC, hghdev commented
> Hi, @hghdev! Can you please squash this into a single commit? Also, you need to run `cmake --build path/to/uncrustify/build --target update-cli-options` to update all the files that are generated from `options.h` and commit those changes also.

Had to learn that. Next iteration.

2021-07-03 15:32 UTC, gmaurel approved these changes

2021-07-03 15:32 UTC, merged