Apply sp_cparen_oparen to parenthesized indirect function calls
uncrustify/uncrustify pull request #3257
Opened 2021-08-03 23:22 UTC by alexhenrie

`sp_cparen_oparen` is the right option to apply to `(get_hello())()`. Furthermore, this patch provides a workaround for issue #3252 because setting `sp_cparen_oparen = ignore` will avoid unwanted space removal in cases where Uncrustify does not parse function pointers correctly.

2021-08-04 15:55 UTC, guy-maurel commented
I am not sure about your diagnostic.
I found a bug at the function do_symbol_check, which make a difference between the lines
#3252:
`void (*x)(void);`
and
`void (*y)(void);`
The code:
`   if (  !pc->flags.test_any(PCF_IN_TYPEDEF | PCF_IN_TEMPLATE)`
makes it impossible to call
`mark_function_type(pc);`
which changes the **x** from **CT_TYPE** to **CT_FUNC_VAR**
Please have a look to my proposal #3258 and comment.

2021-08-05 16:27 UTC, gmaurel requested changes
Please add something such as:
`// Issue #1234`
Should the comment/question: 
 `// Must be an indirect/chained function call?`
stay or can be removed?
Thanks

2021-08-05 17:24 UTC, alexhenrie commented
I have rewritten the comment to be more clear and include the issue number:

```
// Probably a parenthesized indirect function call or similar (issue #3260)
```

2021-08-06 15:13 UTC, gmaurel approved these changes

2021-08-06 15:13 UTC, merged

2021-08-06 17:04 UTC, alexhenrie commented
Thank you!