Don't duplicate leading '//' when sp_cmt_cpp_start=ignore
uncrustify/uncrustify pull request #3273
Opened 2021-08-13 16:16 UTC by alexhenrie

Fixes #3272

2021-08-14 14:00 UTC, gmaurel approved these changes
Fine catch. Thanks

2021-08-14 14:01 UTC, gmaurel requested changes
Fine catch. Thanks.
Please, resolve the confict.

2021-08-14 16:42 UTC, alexhenrie commented
Done

2021-08-15 15:45 UTC, gmaurel approved these changes

2021-08-15 15:45 UTC, merged