Avoid null pointer dereference when formatting function-like macros
uncrustify/uncrustify pull request #3275
Opened 2021-08-14 00:23 UTC by alexhenrie

Fixes #3274

2021-08-14 14:03 UTC, gmaurel commented on src/newlines.cpp
> +                  && (!brace || brace->flags.test(PCF_ONE_LINER)))     // Issue #1511 and #3274
please use:
`brace != nullptr`

2021-08-14 14:04 UTC, gmaurel requested changes
a little change...

2021-08-15 15:51 UTC, gmaurel commented
I like to have:
```.cpp
if (  options::nl_func_leave_one_liners()
   && (  brace == nullptr
         || brace->flags.test(PCF_ONE_LINER)))   // Issue #1511 and #3274
```

2021-08-15 16:20 UTC, alexhenrie commented
Done

2021-08-16 15:02 UTC, gmaurel approved these changes
fine, thanks

2021-08-16 15:02 UTC, merged

2021-08-16 16:30 UTC, alexhenrie commented
Thank you!