Make sure pointers are valid before dereferencing them
uncrustify/uncrustify pull request #3286
Opened 2021-08-17 14:24 UTC by micheleCTDE

As per PR title.
Passed all tests and also tested on about 3200 source files successfully.

2021-08-17 16:14 UTC, gmaurel requested changes
if the next line is 
`  chunk_is_token(...`
it is not necessary to check.
OK?

2021-08-18 01:07 UTC, micheleCTDE commented
> if the next line is ` chunk_is_token(...` it is not necessary to check.

Hi Guy,
I agree with you that a call to 'chunk_is_token()' will basically check that the pointer is valid, and in fact I had also considered that myself. On the other hand the code is relying on it to check a pointer before dereferencing it. If for any reason in future we decide to change the behavior of 'chunk_is_token()' for nullptr, we would leave the door open to potential SEGV when dereferencing the pointer. Having a direct check on the pointer validity will prevent this situation.
What do you think?

If you prefer to keep it as it is now, let me know and I will amend the PR removing the changes where 'chunk_is_token()' is used.

2021-08-18 01:09 UTC, micheleCTDE commented
Btw, rebased on top of current master.

2021-08-18 15:17 UTC, gmaurel approved these changes

2021-08-18 15:17 UTC, merged