Skip template parameters when searching for class constructor
uncrustify/uncrustify pull request #3369
Opened 2021-11-01 20:20 UTC by alexhenrie

Fixes #3368

2021-11-03 18:19 UTC, gmaurel requested changes
have a look to the conflict

2021-11-03 18:45 UTC, alexhenrie commented
The conflict is resolved.

2021-11-05 15:40 UTC, gmaurel approved these changes

2021-11-05 15:40 UTC, merged

2021-11-05 16:36 UTC, alexhenrie commented
Thank you!