Add indent_switch_body option
uncrustify/uncrustify pull request #3372
Opened 2021-11-02 21:30 UTC by alexhenrie

Fixes #3370

2021-11-03 18:23 UTC, gmaurel approved these changes

2021-11-03 18:23 UTC, gmaurel requested changes
have a look to the confilts

2021-11-03 18:46 UTC, alexhenrie commented
The conflict is resolved.

2021-11-05 15:42 UTC, gmaurel approved these changes

2021-11-05 15:42 UTC, merged

2021-11-05 16:37 UTC, alexhenrie commented
Thank you!