A few fixes in cpp parsing and formatting in some corner cases.
uncrustify/uncrustify pull request #3407
Opened 2021-11-26 13:31 UTC by Dandielo

I've started using Uncrustify and found a few issues in my codebase which I hopefully have properly fixed.
The original test are passing, and I've only extended the test cases adding new ones that fail without the fixes.

Here is the current list of the fixes:
* Fixes '&' reference seen as 'BYREF' in 'ARITH' context.
* Fixes lambda wrongly indented if called and not assigned to anything.
* Fixes ')' wrongly indented when 'noexcept' part of the signature.
* Fixes '&' reference seen as 'ARITH' in trailing return 'BYREF' context.

2021-11-26 13:36 UTC, Dandielo commented
Looking through the issues this might close / fix the following: 
* re-opened #3116
* #2205, #3038
* #3284

2021-11-28 16:46 UTC, gmaurel commented on src/combine.cpp
> +            if (chunk_is_token(prev, CT_WORD) && !chunk_is_token(next, CT_NUMBER))
I preffer:
```.cpp
            if (  chunk_is_token(prev, CT_WORD)
               && !chunk_is_token(next, CT_NUMBER))
```

2021-11-28 16:49 UTC, gmaurel commented on src/indent.cpp
> +            bool    enclosure = frm_prev->parent_type != CT_FUNC_DEF && frm_prev != chunk_skip_to_match(frm_prev);
I preffer:
```.cpp
            bool    enclosure = (  frm_prev->parent_type != CT_FUNC_DEF
                                && frm_prev !=
chunk_skip_to_match(frm_prev));
```

2021-11-28 16:54 UTC, gmaurel requested changes
Also add a comment with the Issue #xxxx

2021-11-28 16:55 UTC, gmaurel commented
Fine to see you working on uncrustify,
Thanks.

2021-12-09 22:39 UTC, Dandielo commented
I've updated the code style, so it matches your preferences and added to each location the comment 'Issue #3407' representing this pull request.
If I misunderstood something, please don't hesitate to point it out.

Thanks!

2021-12-10 15:14 UTC, gmaurel approved these changes
Fine, thanks

2021-12-10 15:15 UTC, merged