Add how_to_configure_options.txt file to documentation
uncrustify/uncrustify pull request #3450
Opened 2021-12-29 03:22 UTC by micheleCTDE

As per title and as requested.

2021-12-29 16:50 UTC, gmaurel commented on documentation/how_to_configure_options.txt
> +3. Looking at the file default.cfg, add or change one (or more) options in the config file crated in 2. and test the result of it.
created

2021-12-29 16:52 UTC, gmaurel requested changes
typo

2021-12-30 01:33 UTC, micheleCTDE commented
Fixed + some other minor changes.
Commit was also rebased on top of current master

2021-12-30 16:56 UTC, gmaurel approved these changes

2021-12-30 16:56 UTC, merged