Stops crash reported in Issues #3413 and #3414
uncrustify/uncrustify pull request #3452
Opened 2021-12-30 21:40 UTC by jodyhagins

A stack object was assumed to exist in a vector of stack pointers.

The fix is to create a new stack object when needed.

Note that this does prevent the crash, but I'm not 100% sure that
the generated output is what would be expected.

2021-12-31 16:58 UTC, gmaurel requested changes
fine again
Add the line
fixes #3413
fixes #3414 to close the issues

2021-12-31 17:58 UTC, jodyhagins commented
Apologies again for not knowing how these github things interact.

Where, exactly, do I put those "fixes" lines - in the commit message for this ticket, or some place else?

2022-01-01 00:32 UTC, jodyhagins commented
OK, I added 

fixes #3413
fixes #3414 

to the commit message - I hope that is what you were talking about.

2022-01-01 16:52 UTC, gmaurel approved these changes

2022-01-01 16:52 UTC, merged