Correction of segmentation fault with incomplete list args
uncrustify/uncrustify pull request #3485
Opened 2022-01-23 00:16 UTC by rg-gordienko

./uncrustify -c uncrustifyDefault.cfg main.c --tracking_space

The --tracking_space key is exsist but there is no value as filename.
This is leads to crush of the program. The cause is Args::Params and return of ("").
The return value is not nullptr. It avoid checks for nullptr
before fopen and fopen returns invalid file descriptor.

2022-01-23 13:57 UTC, guy-maurel commented
Please, have a look to:
https://github.com/rg-gordienko/uncrustify/actions
and activate the workflow, thanks.

2022-01-23 14:01 UTC, gmaurel requested changes
You need to uncrustify the source(s) to see if all is OK.

2022-01-24 15:56 UTC, gmaurel approved these changes

2022-01-24 15:56 UTC, gmaurel approved these changes
Fine catch. Thanks.

2022-01-24 15:56 UTC, merged

2022-01-24 15:59 UTC, gmaurel commented
Please, write (next time) such a line:
_fixes #3487_
to get the issue automaticaly closed.

2022-01-24 16:13 UTC, rg-gordienko commented
Ok, Chief! понедельник, 24 января 2022г., 19:00 +03:00 от gmaurel  ***@***.*** :

>Please, write (next time) such a line:
>fixes  #3487
>to get the issue automaticaly closed.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  @ github . com>