Create IsStar and replace it with chunk_is_star
uncrustify/uncrustify pull request #3629
Opened 2022-04-23 12:32 UTC by dundargoc

2022-04-23 12:33 UTC, dundargoc commented
Tried to err on the side of caution and only skip adding `nullptr` if I'm absolutely sure it's not needed.

2022-04-24 06:53 UTC, micheleCTDE requested changes
Please see comments for details

2022-04-24 06:53 UTC, micheleCTDE commented on src/align_stack.cpp
> +      while (  tmp_prev != nullptr
There is no need to test for nullptr here, tmp_prev will never be such.

2022-04-24 06:53 UTC, micheleCTDE commented on src/align_stack.cpp
> +      if (  tmp != nullptr
There is no need to test for nullptr here, tmp_prev will never be such.

2022-04-24 06:53 UTC, micheleCTDE commented on src/align_stack.cpp
> +            || (chunk_is_msref(tmp) && m_star_style == SS_DANGLE))) // TODO: add m_msref_style
The project maintainer (@guy-maurel) prefers to have the various conditions on separate lines.

2022-04-24 06:53 UTC, micheleCTDE commented on src/combine.cpp
> +                       || (  pc->GetNext() != nullptr
"pc->GetNext()" will never return a nullptr by design

2022-04-24 06:53 UTC, micheleCTDE commented on src/combine.cpp
> +      if (tmp != nullptr && tmp->IsStar()) // Issue #2722
There is no need to test for nullptr here, tmp will never be such.

2022-04-24 06:53 UTC, micheleCTDE commented on src/combine_fix_mark.cpp
> +      if (  pc != nullptr
There is no need to test for nullptr here, pc will never be such.

2022-04-24 06:53 UTC, micheleCTDE commented on src/combine_fix_mark.cpp
> +         && (  (tmp1 != nullptr && tmp1->IsStar())
There is no need to test for nullptr here, tmp1 will never be such.

2022-04-24 06:53 UTC, micheleCTDE commented on src/combine_fix_mark.cpp
> +      if (tmp != nullptr && (  tmp->IsStar()
There is no need to test for nullptr here, tmp will never be such.

2022-04-24 06:53 UTC, micheleCTDE commented on src/combine_fix_mark.cpp
> +              && pc != nullptr
There is no need to test for nullptr here, pc will never be such.

2022-04-24 06:57 UTC, micheleCTDE commented
@dundargoc 
Additional note: as you may have noticed, most of the chunk_is_* functons have not been converted into Chunk::* methods yet. This is not a coincidence, but it is to minimize the amount of checking/rework related to nullptr.
The Chunk::Get* methods do not return a nullptr, so once all chunk_get_* functions have been converted, it should be much easier to convert the chunk_is* functions.

2022-04-24 09:22 UTC, dundargoc commented
Aha, yes, that sounds much easier. Thanks for the tip.

2022-04-24 11:16 UTC, dundargoc commented
Shall I squash?

2022-04-24 14:15 UTC, micheleCTDE commented
> Shall I squash?

Would be good :-)

2022-04-26 04:02 UTC, micheleCTDEAdmin approved these changes

2022-04-26 04:03 UTC, micheleCTDE approved these changes

2022-04-26 04:04 UTC, merged

2022-04-26 04:05 UTC, micheleCTDE commented
Thanks!