new option to insert the number of the line
uncrustify/uncrustify pull request #3679
Opened 2022-05-29 15:01 UTC by guy-maurel

at the beginning of each line
for developer only

2022-05-30 04:19 UTC, micheleCTDEAdmin requested changes
New options needs to be added to default.cfg and related files too.

2022-05-31 01:25 UTC, micheleCTDEAdmin requested changes
Minor touch up required related to version number in cfg file.

2022-05-31 01:25 UTC, micheleCTDEAdmin commented on documentation/htdocs/config.txt
> +# Uncrustify_d-0.75.0-60-a7a9d652-dirty
Probably this change was unintentional...

2022-05-31 01:25 UTC, micheleCTDEAdmin commented on documentation/htdocs/default.cfg
> +# Uncrustify_d-0.75.0-60-a7a9d652-dirty
Probably this change was unintentional...

2022-05-31 01:25 UTC, micheleCTDEAdmin commented on etc/defaults.cfg
> +# Uncrustify_d-0.75.0-60-a7a9d652-dirty
Probably this change was unintentional...

2022-05-31 01:25 UTC, micheleCTDEAdmin commented on etc/uigui_uncrustify.ini
> +version=Uncrustify_d-0.75.0-60-a7a9d652-dirty
Probably this change was unintentional...

2022-05-31 11:06 UTC, micheleCTDEAdmin commented
> reflect different things, exactly what we have (a new version)

Yes, I figured you used the /release_tool.py script.
I agree the current version is newer that 0.75, but I don't think it is good to add a hash reference in the config files, especially a temporary one like -dirty. Maybe we can use something like '# Uncrustify_d-0.76.0-development' to indicate that it is a version that will end up in 0.76_f but it is still in development? What do you think?

2022-05-31 14:51 UTC, guy-maurel commented
Yes, I used release_tool.py.
But, using uncrustify  --show-config produce the same line.
Your proposal is fine.
Could you integrate it in the script?
I'll make the change per editor, for just now.

2022-06-01 03:42 UTC, micheleCTDEAdmin approved these changes
Looks good.

2022-06-01 03:43 UTC, merged

2022-06-01 03:43 UTC, micheleCTDEAdmin commented
> Could you integrate it in the script?

I have added this in my TODO list. Will do at some point in coming weeks.