Create unc_ctype.cpp and move in functions from unc_ctype.h.
uncrustify/uncrustify pull request #3683
Opened 2022-05-30 09:18 UTC by dundargoc

2022-05-30 15:47 UTC, gmaurel commented on src/unc_ctype.cpp
> +   if (ch >= -1 && ch <= 255)
please split before && into 2 lines

2022-05-30 15:50 UTC, gmaurel requested changes

2022-05-30 15:50 UTC, gmaurel commented on src/unc_ctype.cpp
> +   return(isalpha(unc_fix_ctype(ch)) && (unc_toupper(unc_fix_ctype(ch)) == ch));
please split before && into 2 lines

2022-05-31 11:10 UTC, micheleCTDEAdmin approved these changes

2022-05-31 11:11 UTC, micheleCTDEAdmin commented
@gmaurel your approval is request too.

2022-06-01 15:01 UTC, merged