Fix some else exprs with indent_ternary_operator==1
uncrustify/uncrustify pull request #3796
Opened 2022-08-12 01:37 UTC by fwojcik

There are a number of valid expressions which do not get indented correctly when
`indent_ternary_operator` is set to 1. Rather than add many more `if()` tests to the
logic in `indent_text()` for these cases, I removed the tests for the `ChunkType` of the
chunk following a `CT_COND_COLON`. I don't think the type should matter when indenting
the 'else' branch, and this change passes the unit tests as well as a full run on my codebase.

Without this fix, all of those ternary statements, except the control group, are mis-indented:
```cpp
namespace ns1 {
int getval(void);
void baz(void);
}

int foo(int in1, int in2, float in3, double in4) {
	int a, b, c, d, e, f, g, h;

	a = (in1 < 10) ? in2 :
	    ns1::getval();

	b = (in1 < 20) ? in2 :
	    int(in3 * 0.4);

	c = (in1 < 30) ? in2 :
	    1.25 * in4;

	d = (in1 < 40) ? in2 :
	    -3;

	e = (in1 < 50) ? in2 :
	    ~3 ^ in1;

	f = (in1 < 60) ? in2 :
	    !(in1 == in2);

	g = (in1 < 70) ? in2 :
	    ++in1;

	h = (in1 < 80) ? in2 :
	                 in1 * 2;

	if ((in1 < 10) ? in2 :
	    ns1::getval()) {
		ns1::baz();
	}

	if ((in1 < 20) ? in2 :
	    int(in3 * 0.4)) {
		ns1::baz();
	}

	if ((in1 < 30) ? in2 :
	    1.25 * in4) {
		ns1::baz();
	}

	if ((in1 < 40) ? in2 :
	    -3) {
		ns1::baz();
	}

	if ((in1 < 50) ? in2 :
	    ~3 ^ in1) {
		ns1::baz();
	}

	if ((in1 < 60) ? in2 :
	    !(in1 == in2)) {
		ns1::baz();
	}

	if ((in1 < 70) ? in2 :
	    ++in1) {
		ns1::baz();
	}

	if ((in1 < 80) ? in2 :
	                 in1 * 2) {
		ns1::baz();
	}

	return a+b+c+d+e+f+g+h;
}
```

2022-08-12 15:14 UTC, gmaurel requested changes

2022-08-12 15:14 UTC, gmaurel commented on tests/expected/cpp/30353-indent_ternary-1.cpp
> +	int a, b, c, d, e, f, g, h;
Please, only one variable per type

2022-08-12 15:23 UTC, fwojcik commented
OK, turned that into a series of variable declarations.

2022-08-13 01:59 UTC, micheleCTDEAdmin approved these changes
Excellent work!

2022-08-13 02:00 UTC, micheleCTDEAdmin commented
@gmaurel 
Waiting for your approval too, before merging

2022-08-13 15:08 UTC, gmaurel approved these changes
Thanks

2022-08-14 01:29 UTC, merged