Check null after malloc() and define trivial destructor C++11
uncrustify/uncrustify pull request #3809
Opened 2022-08-17 08:36 UTC by GermanAizek

@micheleCTDEAdmin, @micheleCTDE

2022-08-19 00:16 UTC, micheleCTDEAdmin requested changes
Please amend as commented.

2022-08-19 00:16 UTC, micheleCTDEAdmin commented on src/compat_win32.cpp
> +      return(false);
we should make sure 'str' is an empty string in this case, since now it would not be updated if we go through the else part.

2022-08-20 01:19 UTC, micheleCTDEAdmin commented
Also this PR is failing the automatic checks. Please fix them too.

2024-06-26 14:55 UTC, guy-maurel commented
replaced by #4341

2024-06-27 16:01 UTC, closed without merging