Fix OC switch case indent when in OC block
uncrustify/uncrustify pull request #3818
Opened 2022-08-21 00:58 UTC by PoeticPete

Fixes #3813

input
```
- (void)func {
  func2(^{
    switch (type) {
      case one:
        break;
      default:
        break;
    }
  });
}
```

bad output (expected to be same as input)
```
- (void)func
{
  func2(^{
    switch (type) {
        case one:
          break;
        default:
          break;
    }
  });
}

```

config
```
indent_switch_case = 2
indent_with_tabs = 0
indent_columns = 2
```

command
```
./uncrustify -l OC+ -c tmp.cfg -f test_file_original.m -o test_file_original_unc.m -p myExample.p -L A 2>myExample.A -ds dump
```

2022-08-21 02:30 UTC, micheleCTDEAdmin requested changes
Comment needs to be amended.

Other than that, it seems a very custom-made solution. How about blocks that are not `switch`? Would probably be better to have a general solution I think. Maybe in that case we don't even need a new bit in the PCF list...

2022-08-21 02:30 UTC, micheleCTDEAdmin commented on src/indent.cpp
> +            // Issue #3183
This is issue #3813, not #3183

2022-08-27 22:29 UTC, PoeticPete commented
#3761 fixed the same issue in cpp and the solution was to check for `PCF_IN_LAMBDA` before running indent logic.

Re: adding additional flag -- If we have a `PCF_IN_LAMBDA` flag, it makes sense to have a flag for OC blocks too?

Re: making this more generalizable -- the issue is that switch cases are falling into the generalized `else` block [here](https://github.com/uncrustify/uncrustify/blame/6ebc9634a21a8f3e7fba713810bdc51514eb86e0/src/indent.cpp#L2006). Basically we are incorrectly assuming the switch block is `({ ... })`. It seems like the other conditions are looking for cases like `({` to determine indent logic, which isn't the case for switch statements.

2022-08-28 01:09 UTC, micheleCTDEAdmin approved these changes
Ok, makes sense. Thanks for the feedback and amending.

2022-08-28 01:09 UTC, merged