Re-Type C++ Access Modifiers in ObjC Message Send
uncrustify/uncrustify pull request #3877
Opened 2022-11-08 22:22 UTC by briantkelley

Tokens inside an Objective-C message send are parsed differently than in other contexts. Parameter names that are spelled the same as C++ access modifiers (e.g. `private:` or Qt's `signals:`) were previously formatted as access modifiers where the parameter name and colon were formatted on their own line with access modifier indentation (e.g. -2) and the argument value on the following line.

This change extends the re-typing logic in `handle_oc_message_send()` to also check for tokens typed as access modifier related.

2022-11-09 18:06 UTC, gmaurel requested changes

2022-11-09 18:06 UTC, gmaurel commented on src/combine.cpp
> +         if (tmp->Is(CT_COLON) || tmp->Is(CT_ACCESS_COLON))
Please use a newline before ||

2022-11-09 19:31 UTC, briantkelley commented on src/combine.cpp
> +         if (tmp->Is(CT_COLON) || tmp->Is(CT_ACCESS_COLON))
Thanks, PR updated!

2022-11-11 10:48 UTC, micheleCTDEAdmin approved these changes
Looks good

2022-11-11 16:01 UTC, gmaurel approved these changes

2022-11-11 16:01 UTC, merged