Option to add space before qualifier, 'operator', class or namespace name, '::'
uncrustify/uncrustify pull request #4073
Opened 2023-08-10 20:31 UTC by Jorengarenar

Fixes #402 and #4071 

New options:

* `sp_before_qualifier_ptr_star` - add or remove space before pointer star '*' that is followed by a qualifier.
* `sp_before_operator_ptr_star` - add or remove space before pointer star '*' that is followed by 'operator' keyword.
* `sp_before_scope_ptr_star` - add or remove space before pointer star '*' that is followed by a class scope (as in `int *MyClass::method()`) or namespace scope (as in `int *my_ns::func()`)
* `sp_before_global_scope_ptr_star` - add or remove space before pointer star '*' that is followed by '::', as in `int *::func()`.

2023-08-19 06:50 UTC, micheleCTDEAdmin requested changes
Three config files seems to have incorrect values (see individual comments). Please amend as necessary.
This also raises the question whether the expected results have been properly reviewed, because I would expect tests 60116 to 60119 to provide different output with the correct options and this wasn't picked up. Please do make sure the expected result is as intended.

2023-08-19 06:50 UTC, micheleCTDEAdmin commented on tests/config/cpp/sp_before_operator_ptr_star-a.cfg
> +sp_before_operator_ptr_star = ignore
Should the value be `add`?

2023-08-19 06:50 UTC, micheleCTDEAdmin commented on tests/config/cpp/sp_before_operator_ptr_star-f.cfg
> +sp_before_operator_ptr_star = ignore
Should the value be `force`?

2023-08-19 06:50 UTC, micheleCTDEAdmin commented on tests/config/cpp/sp_before_operator_ptr_star-r.cfg
> +sp_before_operator_ptr_star = ignore
Should the value be `remove`?

2023-08-19 08:56 UTC, Jorengarenar commented
@micheleCTDEAdmin 
You are absolutely right. When I've split what was supposed to be `sp_before_keyword_ptr_star`, I only updated tests for `sp_before_qualifier_ptr_star` while forgetting about doing the same for `sp_before_operator_ptr_star`.

2023-08-20 07:51 UTC, micheleCTDEAdmin commented
The PR looks good, although when we add new options it would be good to update a bunch of other files too. I know those would get updated at release time eventually, but it is always a good idea to keep etc/defaults.cfg and documentation in line with the contents of options.h
@guy-maurel: ok to merge as is or better to have those files updated as well?

2023-08-21 08:35 UTC, Jorengarenar commented
@micheleCTDEAdmin 
Would there be anything beside `etc/defaults.cfg`? Because if that's all, I think it'd simpler if I just update it right away.

2023-08-21 12:39 UTC, micheleCTDEAdmin commented
> @micheleCTDEAdmin Would there be anything beside `etc/defaults.cfg`? Because if that's all, I think it'd simpler if I just update it right away.

Yes, there are. Look for example at PR 3842, you will see the new option `pp_indent_with_tabs` is added in a bunch of files.

2023-08-22 05:55 UTC, Jorengarenar commented
I've updated config files.  
I didn't bump up the count of options as it refers to release version.  
`etc/uigui_uncrustify.ini` seems to be already quite outdated and options are numbered(?), so I think it may require being generated again in general.

2023-08-22 12:46 UTC, micheleCTDEAdmin commented
> etc/uigui_uncrustify.ini seems to be already quite outdated and options are numbered

This depends on the build (release or debug) if I remember correctly.

2023-08-22 12:47 UTC, micheleCTDEAdmin approved these changes
Looks good to me.

@guy-maurel ok to merge the PR or you want to review first?

2023-08-22 15:57 UTC, guy-maurel commented
OK to merge

2023-08-24 01:58 UTC, merged