Fix global pointer pointing to local variable in uncrustify.cpp bugfix
uncrustify/uncrustify pull request #4226
Opened 2024-02-03 14:06 UTC by JEAYNE

BUG: In uncrustify.cpp the **global** pointer `cdp.html_file` points inside the **local** variable `buffer`.
This PR fixes this bug described in detail in #4216

2024-02-03 16:03 UTC, gmaurel requested changes

2024-02-03 16:03 UTC, gmaurel commented on src/uncrustify.cpp
> +      if (html_file != nullptr && cpd.html_file == nullptr)
Please, put && on the next line.

2024-02-03 16:49 UTC, JEAYNE commented on src/uncrustify.cpp
> +      if (html_file != nullptr && cpd.html_file == nullptr)
Hi Guy,
Done.

2024-02-05 17:22 UTC, gmaurel approved these changes
it is fine, thanks

2024-02-05 17:28 UTC, merged