fix tab indentation for blank lines
uncrustify/uncrustify pull request #4415
Opened 2024-11-20 17:14 UTC by olemayu

Blank lines were indented using spaces even though `indent_with_tabs` specifies that 1 and 2 indent with tabs.
```cfg
indent_single_newlines = true
indent_with_tabs = 1
```

2024-11-20 23:56 UTC, micheleCTDE requested changes
You need to add test cases showing the original problem and the expected fixed version.

2024-11-22 01:45 UTC, micheleCTDE requested changes
The config files should be in the `c` folder and not in the `common` folder. A file is supposed to be in `common` only if it is used in tests by multiple languages.
You can also squash the commit into a single one, since logically they are one entity.
Other than that it looks good.

2024-11-23 00:16 UTC, olemayu commented
There we go! I have never squashed commits before so I hope I did it correctly.

2024-11-23 04:09 UTC, micheleCTDE commented
> There we go! I have never squashed commits before so I hope I did it correctly.

Thanks :-)
Squash was good, although the commit message will need to be adjusted before merging. Currently as result of the squash it has a lot of duplication.
In any case I started the automated tests, so they can all pass first.

2024-11-23 06:56 UTC, micheleCTDE commented
All the automated tests have passed. There is jsut onle thing to do before merging, which is to amend the current commit message from:
```
use tabs for newline column output
add tests

use tabs for newline column output

add tests

move tests
```
to something like:
```
use tabs for newline column output
```

2024-11-30 12:03 UTC, micheleCTDEAdmin approved these changes
It looks good

2024-11-30 13:13 UTC, micheleCTDE approved these changes

2024-11-30 13:13 UTC, merged