a better cli show config
uncrustify/uncrustify pull request #4416
Opened 2024-11-21 17:10 UTC by guy-maurel

2024-11-22 01:24 UTC, micheleCTDE requested changes

2024-11-22 01:24 UTC, micheleCTDE commented on tests/cli/test_cli_options.py
> +    print("Test help is OK")
This `print("Test help is OK")` is not needed here, the help test was already done above

2024-11-23 07:24 UTC, micheleCTDEAdmin approved these changes
Looks good

2024-11-23 16:12 UTC, gmaurel approved these changes

2024-11-23 16:12 UTC, merged